// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqoT124KpScZLbbq300OUqI28Xlwi2DOw',
    appId: '1:808423483984:android:b892d33bbb15c1acb1bf55',
    messagingSenderId: '808423483984',
    projectId: 'fir-fdef7',
    databaseURL: 'https://fir-fdef7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fdef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XED3kyPO7YOlWgwg0g0D4kIG1U94-gc',
    appId: '1:808423483984:ios:957cdaa84e36dcbeb1bf55',
    messagingSenderId: '808423483984',
    projectId: 'fir-fdef7',
    databaseURL: 'https://fir-fdef7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-fdef7.appspot.com',
    iosClientId: '808423483984-v4e9m69rl9k4h99h00vt1bugl5uemets.apps.googleusercontent.com',
    iosBundleId: 'com.ssafy.edu.playground',
  );
}
